### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Dierk** [januslynd/chinook#1]
Hi, nice work! It would be great to share it. 
Is there any release on a maven repo that one can use as a dependency?

**Comment by januslynd** [comment]
Thanks :)

I'm thinking about uploading current binaries to bintray during the day, but I'm still not sure about the versioning and Bintray's restrictions about snapshots. Because is still a beta it could be something like:

chinook-[semantic-versioning]-beta-[commit].jar --> chinook-0.1.0-beta-ef2d2d.jar

I think this way I will be able to overcome Bintray's restrictions. Does it make sense ?

**Comment by Dierk** [comment]
That would be perfect.
While I would also be ok with just making a release with the current state.

**Comment by januslynd** [comment]
Done :)

I've updated README.md to include Bintray repository and Gradle reference. I'm including it here anyway:

```
repositories {
    maven {
        url  "http://dl.bintray.com/januslynd/maven"
    }
}
```

Gradle dependencies:

```
compile 'com.github.januslynd:chinook-core:0.1.0-beta-a3c03ee'
```

I checked the dependency worked by deleting maven and gradle cache and adding the remote dependency directly in the sample module.

While releasing the 0.1.0 I will probably continue to keep using the beta + git-hash convention.

**Comment by Dierk** [comment]
Awesome! Thanks!

**Comment by januslynd** [comment]
:+1:

**Comment by mperry** [comment]
:+1:
