### ISSUE TITLE
Design of native type declarations

### ISSUE THREAD

**Issue by Dierk** [januslynd/chinook#2]
I wonder whether most type declarations should actually be MutableIO rather than just IO. Also the types may not necessarily declared "pure" since e.g. functions that change the value of a request attribute are stateful. Even more so for the response. For the routing I don't know whether the setup can change after server start (possibly not. just checking).

**Comment by januslynd** [comment]
Commenting inline:

Q: "I wonder whether most type declarations should actually be MutableIO rather than just IO"
A:  What are the main advantages to to this change ? It's just that I would like to understand them before doing the change.

Q: " Also the types may not necessarily declared "pure" since e.g. functions that ch..."
A: Agree.

About this last question, the idea was to wrap both the request and the response, so that the "user" is receiving an immutable data structure as the request, and the signature of a given handler would change to:

```
handler :: Request -> Response
```

This way because you're dealing with data structures, you can validate your algebra, without even the necessity of running your app. Does this make any sense to you ?

Anyway, until we get there I will get your suggestion to declare types as not pure :+1:

**Comment by Dierk** [comment]
For Mutable and MutableIO see http://www.frege-lang.org/doc/fregedoc.html PreludeIO. 
In short: it tells the compiler that values of this type may "change under your feet". Not sure if @iwechsu would agree with this abbreviation ;-)

**Comment by januslynd** [comment]
I've started a branch (io_to_mutable_io):

So far I've changed:
- SHA: 392038af90c08c923b3830d38cefed6fbddacf4a
  *\* Response -> MutableIO Response
  *\* Route        -> Mutable Route
- SHA: c27dd63f4fd89de9029a194ade46759398c490b0
  *\* Request -> MutableIO Request

Could you take a look and tell me if I'm in the right direction ? Thanks!

**Comment by Dierk** [comment]
Looks good to me ;-)
Is it still practical for you?

**Comment by januslynd** [comment]
Yes it is, I'm happy knowing that it's both practical and formally correct. Thanks for the feedback :)
